# Generated by Django 4.0.3 on 2022-08-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('Covid19', 'Covid19'), ('Immunization ', 'Immunization ')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='blog_images')),
                ('summary', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
    ]
